server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/campus_db
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.example.grade: DEBUG
    org.springframework.security: DEBUG
